*** Testing ereg() : error conditions ***

Deprecated: Function ereg() is deprecated in %s on line %d

Warning: ereg(): REG_EMPTY in %s on line %d
bool(false)

Deprecated: Function ereg() is deprecated in %s on line %d

Warning: ereg(): REG_EPAREN in %s on line %d
bool(false)

Deprecated: Function ereg() is deprecated in %s on line %d

Warning: ereg(): REG_EBRACK in %s on line %d
bool(false)

Deprecated: Function ereg() is deprecated in %s on line %d

Warning: ereg(): REG_EPAREN in %s on line %d
bool(false)

Deprecated: Function ereg() is deprecated in %s on line %d

Warning: ereg(): REG_BADRPT in %s on line %d
bool(false)

Deprecated: Function ereg() is deprecated in %s on line %d

Warning: ereg(): REG_BADRPT in %s on line %d
bool(false)

Deprecated: Function ereg() is deprecated in %s on line %d

Warning: ereg(): REG_BADRPT in %s on line %d
bool(false)

Deprecated: Function ereg() is deprecated in %s on line %d

Warning: ereg(): REG_BADRPT in %s on line %d
bool(false)

Deprecated: Function ereg() is deprecated in %s on line %d

Warning: ereg(): REG_BADBR in %s on line %d
bool(false)

Deprecated: Function ereg() is deprecated in %s on line %d

Warning: ereg(): REG_EMPTY in %s on line %d
bool(false)

Deprecated: Function ereg() is deprecated in %s on line %d

Warning: ereg(): REG_EMPTY in %s on line %d
bool(false)

Deprecated: Function ereg() is deprecated in %s on line %d

Warning: ereg(): REG_BADBR in %s on line %d
bool(false)

Deprecated: Function ereg() is deprecated in %s on line %d

Warning: ereg(): REG_ERANGE in %s on line %d
bool(false)

Deprecated: Function ereg() is deprecated in %s on line %d

Warning: ereg(): REG_EESCAPE in %s on line %d
bool(false)

Deprecated: Function ereg() is deprecated in %s on line %d

Warning: ereg(): REG_ERANGE in %s on line %d
bool(false)
string(8) "original"
Done