*** Testing ereg_replace() : bad REs ***

Deprecated: Function ereg_replace() is deprecated in %s on line %d

Warning: ereg_replace(): REG_EMPTY in %s on line %d
bool(false)

Deprecated: Function ereg_replace() is deprecated in %s on line %d

Warning: ereg_replace(): REG_EPAREN in %s on line %d
bool(false)

Deprecated: Function ereg_replace() is deprecated in %s on line %d

Warning: ereg_replace(): REG_EBRACK in %s on line %d
bool(false)

Deprecated: Function ereg_replace() is deprecated in %s on line %d

Warning: ereg_replace(): REG_EPAREN in %s on line %d
bool(false)

Deprecated: Function ereg_replace() is deprecated in %s on line %d

Warning: ereg_replace(): REG_BADRPT in %s on line %d
bool(false)

Deprecated: Function ereg_replace() is deprecated in %s on line %d

Warning: ereg_replace(): REG_BADRPT in %s on line %d
bool(false)

Deprecated: Function ereg_replace() is deprecated in %s on line %d

Warning: ereg_replace(): REG_BADRPT in %s on line %d
bool(false)

Deprecated: Function ereg_replace() is deprecated in %s on line %d

Warning: ereg_replace(): REG_BADRPT in %s on line %d
bool(false)

Deprecated: Function ereg_replace() is deprecated in %s on line %d

Warning: ereg_replace(): REG_BADBR in %s on line %d
bool(false)

Deprecated: Function ereg_replace() is deprecated in %s on line %d

Warning: ereg_replace(): REG_EMPTY in %s on line %d
bool(false)

Deprecated: Function ereg_replace() is deprecated in %s on line %d

Warning: ereg_replace(): REG_EMPTY in %s on line %d
bool(false)

Deprecated: Function ereg_replace() is deprecated in %s on line %d

Warning: ereg_replace(): REG_BADBR in %s on line %d
bool(false)

Deprecated: Function ereg_replace() is deprecated in %s on line %d

Warning: ereg_replace(): REG_ERANGE in %s on line %d
bool(false)

Deprecated: Function ereg_replace() is deprecated in %s on line %d

Warning: ereg_replace(): REG_EESCAPE in %s on line %d
bool(false)

Deprecated: Function ereg_replace() is deprecated in %s on line %d

Warning: ereg_replace(): REG_ERANGE in %s on line %d
bool(false)
Done