*** Testing eregi() : error conditions ***

Deprecated: Function eregi() is deprecated in %s on line %d

Warning: eregi(): REG_EMPTY in %s on line %d
bool(false)

Deprecated: Function eregi() is deprecated in %s on line %d

Warning: eregi(): REG_EPAREN in %s on line %d
bool(false)

Deprecated: Function eregi() is deprecated in %s on line %d

Warning: eregi(): REG_EBRACK in %s on line %d
bool(false)

Deprecated: Function eregi() is deprecated in %s on line %d

Warning: eregi(): REG_EPAREN in %s on line %d
bool(false)

Deprecated: Function eregi() is deprecated in %s on line %d

Warning: eregi(): REG_BADRPT in %s on line %d
bool(false)

Deprecated: Function eregi() is deprecated in %s on line %d

Warning: eregi(): REG_BADRPT in %s on line %d
bool(false)

Deprecated: Function eregi() is deprecated in %s on line %d

Warning: eregi(): REG_BADRPT in %s on line %d
bool(false)

Deprecated: Function eregi() is deprecated in %s on line %d

Warning: eregi(): REG_BADRPT in %s on line %d
bool(false)

Deprecated: Function eregi() is deprecated in %s on line %d

Warning: eregi(): REG_BADBR in %s on line %d
bool(false)

Deprecated: Function eregi() is deprecated in %s on line %d

Warning: eregi(): REG_EMPTY in %s on line %d
bool(false)

Deprecated: Function eregi() is deprecated in %s on line %d

Warning: eregi(): REG_EMPTY in %s on line %d
bool(false)

Deprecated: Function eregi() is deprecated in %s on line %d

Warning: eregi(): REG_BADBR in %s on line %d
bool(false)

Deprecated: Function eregi() is deprecated in %s on line %d

Warning: eregi(): REG_ERANGE in %s on line %d
bool(false)

Deprecated: Function eregi() is deprecated in %s on line %d

Warning: eregi(): REG_EESCAPE in %s on line %d
bool(false)

Deprecated: Function eregi() is deprecated in %s on line %d

Warning: eregi(): REG_ERANGE in %s on line %d
bool(false)
string(8) "original"
Done