*** Testing split() : usage variations ***
Error: 8 - Undefined variable: undefined_var, %s(64)
Error: 8 - Undefined variable: unset_var, %s(67)

Arg value 0 
Error: 8192 - Function split() is deprecated, %s(74)
array(1) {
  [0]=>
  string(1) "0"
}

Arg value 1 
Error: 8192 - Function split() is deprecated, %s(74)
array(1) {
  [0]=>
  string(1) "1"
}

Arg value 12345 
Error: 8192 - Function split() is deprecated, %s(74)
array(1) {
  [0]=>
  string(5) "12345"
}

Arg value -2345 
Error: 8192 - Function split() is deprecated, %s(74)
array(1) {
  [0]=>
  string(5) "-2345"
}

Arg value 10.5 
Error: 8192 - Function split() is deprecated, %s(74)
array(1) {
  [0]=>
  string(4) "10.5"
}

Arg value -10.5 
Error: 8192 - Function split() is deprecated, %s(74)
array(1) {
  [0]=>
  string(5) "-10.5"
}

Arg value 101234567000 
Error: 8192 - Function split() is deprecated, %s(74)
array(1) {
  [0]=>
  string(12) "101234567000"
}

Arg value 1.07654321E-9 
Error: 8192 - Function split() is deprecated, %s(74)
array(2) {
  [0]=>
  string(10) "1.07654321"
  [1]=>
  string(2) "-9"
}

Arg value 0.5 
Error: 8192 - Function split() is deprecated, %s(74)
array(1) {
  [0]=>
  string(3) "0.5"
}
Error: 8 - Array to string conversion, %ssplit_variation_002.php(%d)

Arg value Array 
Error: 8192 - Function split() is deprecated, %s(74)
Error: 2 - split() expects parameter 2 to be string, array given, %s(74)
NULL
Error: 8 - Array to string conversion, %ssplit_variation_002.php(%d)

Arg value Array 
Error: 8192 - Function split() is deprecated, %s(74)
Error: 2 - split() expects parameter 2 to be string, array given, %s(74)
NULL
Error: 8 - Array to string conversion, %ssplit_variation_002.php(%d)

Arg value Array 
Error: 8192 - Function split() is deprecated, %s(74)
Error: 2 - split() expects parameter 2 to be string, array given, %s(74)
NULL
Error: 8 - Array to string conversion, %ssplit_variation_002.php(%d)

Arg value Array 
Error: 8192 - Function split() is deprecated, %s(74)
Error: 2 - split() expects parameter 2 to be string, array given, %s(74)
NULL
Error: 8 - Array to string conversion, %ssplit_variation_002.php(%d)

Arg value Array 
Error: 8192 - Function split() is deprecated, %s(74)
Error: 2 - split() expects parameter 2 to be string, array given, %s(74)
NULL

Arg value  
Error: 8192 - Function split() is deprecated, %s(74)
array(1) {
  [0]=>
  string(0) ""
}

Arg value  
Error: 8192 - Function split() is deprecated, %s(74)
array(1) {
  [0]=>
  string(0) ""
}

Arg value 1 
Error: 8192 - Function split() is deprecated, %s(74)
array(1) {
  [0]=>
  string(1) "1"
}

Arg value  
Error: 8192 - Function split() is deprecated, %s(74)
array(1) {
  [0]=>
  string(0) ""
}

Arg value 1 
Error: 8192 - Function split() is deprecated, %s(74)
array(1) {
  [0]=>
  string(1) "1"
}

Arg value  
Error: 8192 - Function split() is deprecated, %s(74)
array(1) {
  [0]=>
  string(0) ""
}

Arg value  
Error: 8192 - Function split() is deprecated, %s(74)
array(1) {
  [0]=>
  string(0) ""
}

Arg value  
Error: 8192 - Function split() is deprecated, %s(74)
array(1) {
  [0]=>
  string(0) ""
}
Error: 4096 - Object of class stdClass could not be converted to string, %s(73)

Arg value  
Error: 8192 - Function split() is deprecated, %s(74)
Error: 2 - split() expects parameter 2 to be string, object given, %s(74)
NULL

Arg value  
Error: 8192 - Function split() is deprecated, %s(74)
array(1) {
  [0]=>
  string(0) ""
}

Arg value  
Error: 8192 - Function split() is deprecated, %s(74)
array(1) {
  [0]=>
  string(0) ""
}
Done