*** Testing split() : error conditions ***

Deprecated: Function split() is deprecated in %s on line %d

Warning: split(): REG_EMPTY in %s on line %d
bool(false)

Deprecated: Function split() is deprecated in %s on line %d

Warning: split(): REG_EPAREN in %s on line %d
bool(false)

Deprecated: Function split() is deprecated in %s on line %d

Warning: split(): REG_EBRACK in %s on line %d
bool(false)

Deprecated: Function split() is deprecated in %s on line %d

Warning: split(): REG_EPAREN in %s on line %d
bool(false)

Deprecated: Function split() is deprecated in %s on line %d

Warning: split(): REG_BADRPT in %s on line %d
bool(false)

Deprecated: Function split() is deprecated in %s on line %d

Warning: split(): REG_BADRPT in %s on line %d
bool(false)

Deprecated: Function split() is deprecated in %s on line %d

Warning: split(): REG_BADRPT in %s on line %d
bool(false)

Deprecated: Function split() is deprecated in %s on line %d

Warning: split() expects parameter 3 to be long, string given in %s on line %d
NULL

Deprecated: Function split() is deprecated in %s on line %d

Warning: split(): REG_BADBR in %s on line %d
bool(false)

Deprecated: Function split() is deprecated in %s on line %d

Warning: split(): REG_EMPTY in %s on line %d
bool(false)

Deprecated: Function split() is deprecated in %s on line %d

Warning: split(): REG_EMPTY in %s on line %d
bool(false)

Deprecated: Function split() is deprecated in %s on line %d

Warning: split(): REG_BADBR in %s on line %d
bool(false)

Deprecated: Function split() is deprecated in %s on line %d

Warning: split(): REG_ERANGE in %s on line %d
bool(false)

Deprecated: Function split() is deprecated in %s on line %d

Warning: split(): REG_EESCAPE in %s on line %d
bool(false)

Deprecated: Function split() is deprecated in %s on line %d

Warning: split() expects parameter 3 to be long, string given in %s on line %d
NULL
string(8) "original"
Done